# Run benchmarks on a remote system according to 
# resources/release-benchmark-docker-compose.yml
# - Calls the reusable worflow remote-benchmarks.yml
# - Used for testing the full workflow without affecting 
#   permanent data in other categoriees (like release, nightly)
# - Produces temporary data that is not preserved long term 

name: Adhoc Benchmark Test on Docker Deephaven

on:
  workflow_dispatch:
   inputs:
     docker_image:
       description: 'Docker Image Name or DH Core Branch'
       required: true
       default: 'edge'
       type: string
     run_label:
       description: 'Set Label'
       required: true
       type: string
       default: ''
     test_package:
       description: 'Benchmark Test Package'
       required: true
       default: 'io.deephaven.benchmark.tests.standard'
       type: string
     test_class_regex:
       description: 'Benchmark Test Class Pattern'
       required: true
       default: '^.*[.]MixedCombo.*Test.*$'
       type: string
     test_iterations:
       description: 'Benchmark Iterations'
       required: true
       default: '1'
       type: string
     scale_row_count:
       description: 'Benchmark Scale Row Count'
       required: true
       default: '1000000'
       type: string
     distribution:
       description: 'Benchmark Data Distribution'
       required: true
       default: 'random'
       type: choice
       options: 
       - random
       - ascending
       - descending
       - runlength

jobs:
  process-adhoc-benchmarks:
    if: ${{github.repository_owner != 'deephaven'}}
    uses: ./.github/workflows/remote-benchmarks.yml
    with:
      run_type: adhoc
      docker_image: ${{ inputs.docker_image }}
      run_label: ${{ inputs.run_label }}
      test_package: ${{ inputs.test_package }}
      test_class_regex: ${{ inputs.test_class_regex }}
      test_iterations: ${{ inputs.test_iterations }}
      scale_row_count: ${{ inputs.scale_row_count }}
      distribution: ${{ inputs.distribution }}
    secrets: inherit


